# Generated by Django 4.0.1 on 2022-01-11 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='model',
            field=models.CharField(choices=[('Lightweight', 'Lightweight'), ('Middleweight', 'Middleweight'), ('Cruiserweight', 'Cruiserweight'), ('Heavyweight', 'Heavyweight')], max_length=13, verbose_name='Model'),
        ),
    ]
