# Generated by Django 4.0.1 on 2022-01-11 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_delivery', '0002_alter_drone_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=350, null=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Weight')),
                ('code', models.CharField(max_length=150, verbose_name='Code')),
                ('height', models.PositiveIntegerField(blank=True, default=0, editable=False, null=True)),
                ('width', models.PositiveIntegerField(blank=True, default=0, editable=False, null=True)),
                ('image', models.ImageField(height_field='height', upload_to='medications/%Y/%m/%d/', verbose_name='Image', width_field='width')),
            ],
        ),
    ]
