# Generated by Django 4.0.1 on 2022-01-12 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drone_delivery', '0003_medication'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=350, null=True, verbose_name='Slug')),
                ('drone', models.ForeignKey(limit_choices_to=models.Q(('state', 'IDLE'), ('battery_capacity_gte', 25), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='assigned_drone', to='drone_delivery.drone', verbose_name='Assigned Drone')),
                ('medications', models.ManyToManyField(related_name='items', to='drone_delivery.Medication', verbose_name='Medications Items')),
            ],
        ),
    ]
