# Generated by Django 4.0.1 on 2022-01-15 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drone_delivery', '0005_alter_deliverypackage_drone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverypackage',
            options={'verbose_name': 'Delivery Package', 'verbose_name_plural': 'Deliveries Packages'},
        ),
        migrations.AlterField(
            model_name='deliverypackage',
            name='drone',
            field=models.ForeignKey(limit_choices_to=models.Q(('state', 'IDLE'), ('battery_capacity__gte', 25)), on_delete=django.db.models.deletion.CASCADE, to='drone_delivery.drone', verbose_name='Assigned Drone'),
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=350, null=True, verbose_name='Slug')),
                ('qty', models.PositiveSmallIntegerField(default=1, verbose_name='Qty')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drone_delivery.medication', verbose_name='Medication')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
            },
        ),
    ]
