# Generated by Django 4.0.1 on 2022-01-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_delivery', '0006_alter_deliverypackage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medication',
            options={'verbose_name': 'Medication', 'verbose_name_plural': 'Medications'},
        ),
        migrations.RemoveField(
            model_name='deliverypackage',
            name='medications',
        ),
        migrations.AddField(
            model_name='deliverypackage',
            name='package',
            field=models.ManyToManyField(to='drone_delivery.Package', verbose_name='Medications Items'),
        ),
        migrations.AddField(
            model_name='package',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='package',
            unique_together={('medication', 'qty', 'created')},
        ),
    ]
