# Generated by Django 4.0.1 on 2022-01-16 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drone_delivery', '0007_alter_medication_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='package',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='package',
            name='created',
        ),
    ]
