# Generated by Django 4.0.1 on 2022-01-16 07:21

from django.db import migrations, models
import drone_delivery.validators


class Migration(migrations.Migration):

    dependencies = [
        ('drone_delivery', '0008_alter_package_unique_together_remove_package_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypackage',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Created'),
        ),
        migrations.AddField(
            model_name='package',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='drone',
            name='weight_limit',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=5, verbose_name='Weight Limit'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='code',
            field=models.CharField(max_length=150, validators=[drone_delivery.validators.validate_medication_code], verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(max_length=150, unique=True, validators=[drone_delivery.validators.validate_medication_name], verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='package',
            unique_together={('medication', 'qty', 'created')},
        ),
    ]
